# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['v2.0.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('Monster.py', '.'),
        ('Player.py', '.'),
        ('Upgrade.py', '.'),
        ('LICENSE', '.'),
        ('__init__.py', '.'),
        ('__pycache__/Frames.cpython-312.pyc', '__pycache__'),
        ('__pycache__/Game.cpython-312.pyc', '__pycache__'),
        ('__pycache__/Monster.cpython-312.pyc', '__pycache__'),
        ('__pycache__/Player.cpython-312.pyc', '__pycache__'),
        ('__pycache__/Upgrade.cpython-312.pyc', '__pycache__'),
	    ('assets/SoulWoods.ico', 'assets'),
        ('assets/MainScreen/ACKButton.png', 'assets/MainScreen'),
        ('assets/MainScreen/Attack.png', 'assets/MainScreen'),
        ('assets/MainScreen/Guard.png', 'assets/MainScreen'),
        ('assets/MainScreen/MainScreenRoot1.png', 'assets/MainScreen'),
        ('assets/MainScreen/MainScreenRoot2.png', 'assets/MainScreen'),
        ('assets/MainScreen/MainScreenRoot3.png', 'assets/MainScreen'),
        ('assets/MainScreen/MonsterAttack1.png', 'assets/MainScreen'),
        ('assets/MainScreen/MonsterAttack2.png', 'assets/MainScreen'),
        ('assets/MainScreen/MonsterAttack3.png', 'assets/MainScreen'),
        ('assets/MainScreen/MonsterDEATH1.png', 'assets/MainScreen'),
        ('assets/MainScreen/MonsterDEATH2.png', 'assets/MainScreen'),
        ('assets/MainScreen/MonsterDEATH3.png', 'assets/MainScreen'),
        ('assets/MainScreen/MonsterHURT.png', 'assets/MainScreen'),
        ('assets/MainScreen/MonsterIDLE.png', 'assets/MainScreen'),
        ('assets/MainScreen/monsterStatWindow.png', 'assets/MainScreen'),
        ('assets/MainScreen/PlayerAttack1.png', 'assets/MainScreen'),
        ('assets/MainScreen/PlayerAttack2.png', 'assets/MainScreen'),
        ('assets/MainScreen/PlayerAttack3.png', 'assets/MainScreen'),
        ('assets/MainScreen/PlayerHURT.png', 'assets/MainScreen'),
        ('assets/MainScreen/PlayerIDLE.png', 'assets/MainScreen'),
        ('assets/MainScreen/playerStatWindow.png', 'assets/MainScreen'),
        ('assets/MainScreen/shieldB.png', 'assets/MainScreen'),
        ('assets/MainScreen/swingB.png', 'assets/MainScreen'),
        ('assets/MainScreen/UpgradeAttack.png', 'assets/MainScreen'),
        ('assets/MainScreen/UpgradeHP.png', 'assets/MainScreen'),
        ('assets/MainScreen/UpgradeSpeed.png', 'assets/MainScreen'),
        ('assets/StartupScreen/1.png', 'assets/StartupScreen'),
        ('assets/StartupScreen/Button1.png', 'assets/StartupScreen'),
        ('assets/StartupScreen/Button2.png', 'assets/StartupScreen'),
        ('assets/StartupScreen/Button3.png', 'assets/StartupScreen'),
        ('assets/Story/0.png', 'assets/Story'),
        ('assets/Story/1.png', 'assets/Story'),
        ('assets/Story/2.png', 'assets/Story'),
        ('assets/Story/3.png', 'assets/Story'),
        ('assets/Story/4.png', 'assets/Story'),
        ('assets/Story/5.png', 'assets/Story'),
        ('assets/Story/6.png', 'assets/Story'),
        ('assets/Story/7.png', 'assets/Story'),
        ('assets/Story/8.png', 'assets/Story'),
        ('assets/Story/9.png', 'assets/Story'),
        ('assets/Story/10.png', 'assets/Story'),
        ('assets/Story/1000.png', 'assets/Story'),
        ('assets/Story/bg.png', 'assets/Story'),
        ('assets/Story/Button1.png', 'assets/Story'),
        ('assets/Story/Button2.png', 'assets/Story'),
        ('assets/Story/Button3.png', 'assets/Story'),
    ],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SoulWoods',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    windowed=True,
    icon='assets/Soulwoods.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SoulWoods',
)
