# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('GAME.py', '.'),
        ('PLAYER.py', '.'),
        ('WORLD.py', '.'),
        ('LICENSE', '.'),
        ('__init__.py', '.'),
        ('SOULWOODS.py', '.'),
        ('engine/__pycache__', 'engine/__pycache__'),
        ('assets/GameEssential/icon.ico', 'assets/GameEssential'),
        ('assets/Player/IDLERIGHT', 'assets/Player/IDLERIGHT'),
        ('assets/Player/IDLELEFT', 'assets/Player/IDLELEFT'),
        ('assets/Player/RUNLEFT', 'assets/Player/RUNLEFT'),
        ('assets/Player/RUNRIGHT', 'assets/Player/RUNRIGHT'),
        ('assets/Player/JUMPLEFT', 'assets/Player/JUMPLEFT'),
        ('assets/Player/JUMPRIGHT', 'assets/Player/JUMPRIGHT'),
        ('assets/Environment/Empty', 'assets/Environment/Empty'),
        ('assets/Environment/Dirt', 'assets/Environment/Dirt'),
        ('assets/Environment/Grass', 'assets/Environment/Grass'),
        ('assets/Environment/Grass/Stone', 'assets/Environment/Grass/Stone'),
        ('assets/Environment/Grass/Logs', 'assets/Environment/Grass/Logs'),
        ('assets/Environment/Ice', 'assets/Environment/Ice'),
        ('assets/Environment/Stone', 'assets/Environment/Stone'),
        ('assets/Environment/StoneDry', 'assets/Environment/StoneDry'),
        ('assets/Environment/StoneWet', 'assets/Environment/StoneWet'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SoulWoods',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    windowed=True,
    icon='assets/GameEssential/icon.ico',
)

coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='SoulWoods')  # Replace with your actual project name