import customtkinter as ctk
import tkinter as tk
import random
class WORLD():
    def __init__(self,GAMEINSTANCE):
        self.CANVAS = tk.Canvas(GAMEINSTANCE.GAME,background="#000000",borderwidth=0,highlightthickness=0)
        self.CANVAS.place(anchor=tk.CENTER,relheight=1,relwidth=1,relx=0.5,rely=0.5)
        
        self.ENVIRONMENTEMPTY = tk.PhotoImage(file="bin/assets/Environment/Empty/0.png")
        self.ENVIRONMENTEMPTYSCALED = self.ENVIRONMENTEMPTY.subsample(2,2)
        
        self.ENVIRONMENTDIRT1 = tk.PhotoImage(file="bin/assets/Environment/Dirt/1.png")
        self.ENVIRONMENTDIRT1SCALED = self.ENVIRONMENTDIRT1.subsample(2, 2)
        self.ENVIRONMENTDIRT2 = tk.PhotoImage(file="bin/assets/Environment/Dirt/2.png")
        self.ENVIRONMENTDIRT2SCALED = self.ENVIRONMENTDIRT2.subsample(2, 2)
        self.ENVIRONMENTDIRT3 = tk.PhotoImage(file="bin/assets/Environment/Dirt/3.png")
        self.ENVIRONMENTDIRT3SCALED = self.ENVIRONMENTDIRT3.subsample(2, 2)
        self.ENVIRONMENTDIRT4 = tk.PhotoImage(file="bin/assets/Environment/Dirt/4.png")
        self.ENVIRONMENTDIRT4SCALED = self.ENVIRONMENTDIRT4.subsample(2, 2)
        self.ENVIRONMENTDIRT5 = tk.PhotoImage(file="bin/assets/Environment/Dirt/5.png")
        self.ENVIRONMENTDIRT5SCALED = self.ENVIRONMENTDIRT5.subsample(2, 2)
        self.ENVIRONMENTDIRT6 = tk.PhotoImage(file="bin/assets/Environment/Dirt/6.png")
        self.ENVIRONMENTDIRT6SCALED = self.ENVIRONMENTDIRT6.subsample(2, 2)
        self.ENVIRONMENTDIRT7 = tk.PhotoImage(file="bin/assets/Environment/Dirt/7.png")
        self.ENVIRONMENTDIRT7SCALED = self.ENVIRONMENTDIRT7.subsample(2, 2)
        self.ENVIRONMENTDIRT8 = tk.PhotoImage(file="bin/assets/Environment/Dirt/8.png")
        self.ENVIRONMENTDIRT8SCALED = self.ENVIRONMENTDIRT8.subsample(2, 2)
        self.ENVIRONMENTDIRT9 = tk.PhotoImage(file="bin/assets/Environment/Dirt/9.png")
        self.ENVIRONMENTDIRT9SCALED = self.ENVIRONMENTDIRT9.subsample(2, 2)
        self.ENVIRONMENTDIRT10 = tk.PhotoImage(file="bin/assets/Environment/Dirt/10.png")
        self.ENVIRONMENTDIRT10SCALED = self.ENVIRONMENTDIRT10.subsample(2, 2)
        self.ENVIRONMENTDIRT11 = tk.PhotoImage(file="bin/assets/Environment/Dirt/11.png")
        self.ENVIRONMENTDIRT11SCALED = self.ENVIRONMENTDIRT11.subsample(2, 2)
        self.ENVIRONMENTDIRT12 = tk.PhotoImage(file="bin/assets/Environment/Dirt/12.png")
        self.ENVIRONMENTDIRT12SCALED = self.ENVIRONMENTDIRT12.subsample(2, 2)
        self.ENVIRONMENTDIRT13 = tk.PhotoImage(file="bin/assets/Environment/Dirt/13.png")
        self.ENVIRONMENTDIRT13SCALED = self.ENVIRONMENTDIRT13.subsample(2, 2)
        self.ENVIRONMENTDIRT14 = tk.PhotoImage(file="bin/assets/Environment/Dirt/14.png")
        self.ENVIRONMENTDIRT14SCALED = self.ENVIRONMENTDIRT14.subsample(2, 2)
        self.ENVIRONMENTDIRT15 = tk.PhotoImage(file="bin/assets/Environment/Dirt/15.png")
        self.ENVIRONMENTDIRT15SCALED = self.ENVIRONMENTDIRT15.subsample(2, 2)
        self.ENVIRONMENTDIRT16 = tk.PhotoImage(file="bin/assets/Environment/Dirt/16.png")
        self.ENVIRONMENTDIRT16SCALED = self.ENVIRONMENTDIRT16.subsample(2, 2)
        self.ENVIRONMENTDIRT17 = tk.PhotoImage(file="bin/assets/Environment/Dirt/17.png")
        self.ENVIRONMENTDIRT17SCALED = self.ENVIRONMENTDIRT17.subsample(2, 2)
        self.ENVIRONMENTDIRT18 = tk.PhotoImage(file="bin/assets/Environment/Dirt/18.png")
        self.ENVIRONMENTDIRT18SCALED = self.ENVIRONMENTDIRT18.subsample(2, 2)
        self.ENVIRONMENTDIRT19 = tk.PhotoImage(file="bin/assets/Environment/Dirt/19.png")
        self.ENVIRONMENTDIRT19SCALED = self.ENVIRONMENTDIRT19.subsample(2, 2)
        self.ENVIRONMENTDIRT20 = tk.PhotoImage(file="bin/assets/Environment/Dirt/20.png")
        self.ENVIRONMENTDIRT20SCALED = self.ENVIRONMENTDIRT20.subsample(2, 2)
        self.ENVIRONMENTDIRT21 = tk.PhotoImage(file="bin/assets/Environment/Dirt/21.png")
        self.ENVIRONMENTDIRT21SCALED = self.ENVIRONMENTDIRT21.subsample(2, 2)
        self.ENVIRONMENTDIRT22 = tk.PhotoImage(file="bin/assets/Environment/Dirt/22.png")
        self.ENVIRONMENTDIRT22SCALED = self.ENVIRONMENTDIRT22.subsample(2, 2)
        self.ENVIRONMENTDIRT23 = tk.PhotoImage(file="bin/assets/Environment/Dirt/23.png")
        self.ENVIRONMENTDIRT23SCALED = self.ENVIRONMENTDIRT23.subsample(2, 2)
        self.ENVIRONMENTDIRT24 = tk.PhotoImage(file="bin/assets/Environment/Dirt/24.png")
        self.ENVIRONMENTDIRT24SCALED = self.ENVIRONMENTDIRT24.subsample(2, 2)
        
        self.ENVIRONMENTGRASS1 = tk.PhotoImage(file="bin/assets/Environment/Grass/1.png")
        self.ENVIRONMENTGRASS1SCALED = self.ENVIRONMENTGRASS1.subsample(2, 2)
        self.ENVIRONMENTGRASS2 = tk.PhotoImage(file="bin/assets/Environment/Grass/2.png")
        self.ENVIRONMENTGRASS2SCALED = self.ENVIRONMENTGRASS2.subsample(2, 2)
        self.ENVIRONMENTGRASS3 = tk.PhotoImage(file="bin/assets/Environment/Grass/3.png")
        self.ENVIRONMENTGRASS3SCALED = self.ENVIRONMENTGRASS3.subsample(2, 2)
        self.ENVIRONMENTGRASS4 = tk.PhotoImage(file="bin/assets/Environment/Grass/4.png")
        self.ENVIRONMENTGRASS4SCALED = self.ENVIRONMENTGRASS4.subsample(2, 2)
        self.ENVIRONMENTGRASS5 = tk.PhotoImage(file="bin/assets/Environment/Grass/5.png")
        self.ENVIRONMENTGRASS5SCALED = self.ENVIRONMENTGRASS5.subsample(2, 2)
        self.ENVIRONMENTGRASS6 = tk.PhotoImage(file="bin/assets/Environment/Grass/6.png")
        self.ENVIRONMENTGRASS6SCALED = self.ENVIRONMENTGRASS6.subsample(2, 2)
        self.ENVIRONMENTGRASS7 = tk.PhotoImage(file="bin/assets/Environment/Grass/7.png")
        self.ENVIRONMENTGRASS7SCALED = self.ENVIRONMENTGRASS7.subsample(2, 2)
        self.ENVIRONMENTGRASS8 = tk.PhotoImage(file="bin/assets/Environment/Grass/8.png")
        self.ENVIRONMENTGRASS8SCALED = self.ENVIRONMENTGRASS8.subsample(2, 2)
        self.ENVIRONMENTGRASS9 = tk.PhotoImage(file="bin/assets/Environment/Grass/9.png")
        self.ENVIRONMENTGRASS9SCALED = self.ENVIRONMENTGRASS9.subsample(2, 2)
        self.ENVIRONMENTGRASS10 = tk.PhotoImage(file="bin/assets/Environment/Grass/10.png")
        self.ENVIRONMENTGRASS10SCALED = self.ENVIRONMENTGRASS10.subsample(2, 2)
        self.ENVIRONMENTGRASS11 = tk.PhotoImage(file="bin/assets/Environment/Grass/11.png")
        self.ENVIRONMENTGRASS11SCALED = self.ENVIRONMENTGRASS11.subsample(2, 2)
        self.ENVIRONMENTGRASS12 = tk.PhotoImage(file="bin/assets/Environment/Grass/12.png")
        self.ENVIRONMENTGRASS12SCALED = self.ENVIRONMENTGRASS12.subsample(2, 2)
        self.ENVIRONMENTGRASS13 = tk.PhotoImage(file="bin/assets/Environment/Grass/13.png")
        self.ENVIRONMENTGRASS13SCALED = self.ENVIRONMENTGRASS13.subsample(2, 2)
        self.ENVIRONMENTGRASS14 = tk.PhotoImage(file="bin/assets/Environment/Grass/14.png")
        self.ENVIRONMENTGRASS14SCALED = self.ENVIRONMENTGRASS14.subsample(2, 2)
        self.ENVIRONMENTGRASS15 = tk.PhotoImage(file="bin/assets/Environment/Grass/15.png")
        self.ENVIRONMENTGRASS15SCALED = self.ENVIRONMENTGRASS15.subsample(2, 2)
        self.ENVIRONMENTGRASS16 = tk.PhotoImage(file="bin/assets/Environment/Grass/16.png")
        self.ENVIRONMENTGRASS16SCALED = self.ENVIRONMENTGRASS16.subsample(2, 2)
        
        self.ENVIRONMENTGRASSSTONE1 = tk.PhotoImage(file="bin/assets/Environment/Grass/Stone/1.png")
        self.ENVIRONMENTGRASSSTONE1SCALED = self.ENVIRONMENTGRASSSTONE1.subsample(2, 2)
        self.ENVIRONMENTGRASSSTONE2 = tk.PhotoImage(file="bin/assets/Environment/Grass/Stone/2.png")
        self.ENVIRONMENTGRASSSTONE2SCALED = self.ENVIRONMENTGRASSSTONE2.subsample(2, 2)
        self.ENVIRONMENTGRASSSTONE3 = tk.PhotoImage(file="bin/assets/Environment/Grass/Stone/3.png")
        self.ENVIRONMENTGRASSSTONE3SCALED = self.ENVIRONMENTGRASSSTONE3.subsample(2, 2)
        self.ENVIRONMENTGRASSSTONE4 = tk.PhotoImage(file="bin/assets/Environment/Grass/Stone/4.png")
        self.ENVIRONMENTGRASSSTONE4SCALED = self.ENVIRONMENTGRASSSTONE4.subsample(2, 2)
        self.ENVIRONMENTGRASSSTONE5 = tk.PhotoImage(file="bin/assets/Environment/Grass/Stone/5.png")
        self.ENVIRONMENTGRASSSTONE5SCALED = self.ENVIRONMENTGRASSSTONE5.subsample(2, 2)
        self.ENVIRONMENTGRASSSTONE6 = tk.PhotoImage(file="bin/assets/Environment/Grass/Stone/6.png")
        self.ENVIRONMENTGRASSSTONE6SCALED = self.ENVIRONMENTGRASSSTONE6.subsample(2, 2)
        self.ENVIRONMENTGRASSSTONE7 = tk.PhotoImage(file="bin/assets/Environment/Grass/Stone/7.png")
        self.ENVIRONMENTGRASSSTONE7SCALED = self.ENVIRONMENTGRASSSTONE7.subsample(2, 2)
        self.ENVIRONMENTGRASSSTONE8 = tk.PhotoImage(file="bin/assets/Environment/Grass/Stone/8.png")
        self.ENVIRONMENTGRASSSTONE8SCALED = self.ENVIRONMENTGRASSSTONE8.subsample(2, 2)
        
        self.ENVIRONMENTGRASSLOGS1 = tk.PhotoImage(file="bin/assets/Environment/Grass/Logs/1.png")
        self.ENVIRONMENTGRASSLOGS1SCALED = self.ENVIRONMENTGRASSLOGS1.subsample(2, 2)
        self.ENVIRONMENTGRASSLOGS2 = tk.PhotoImage(file="bin/assets/Environment/Grass/Logs/2.png")
        self.ENVIRONMENTGRASSLOGS2SCALED = self.ENVIRONMENTGRASSLOGS2.subsample(2, 2)
        self.ENVIRONMENTGRASSLOGS3 = tk.PhotoImage(file="bin/assets/Environment/Grass/Logs/3.png")
        self.ENVIRONMENTGRASSLOGS3SCALED = self.ENVIRONMENTGRASSLOGS3.subsample(2, 2)
        self.ENVIRONMENTGRASSLOGS4 = tk.PhotoImage(file="bin/assets/Environment/Grass/Logs/4.png")
        self.ENVIRONMENTGRASSLOGS4SCALED = self.ENVIRONMENTGRASSLOGS4.subsample(2, 2)
        self.ENVIRONMENTGRASSLOGS5 = tk.PhotoImage(file="bin/assets/Environment/Grass/Logs/5.png")
        self.ENVIRONMENTGRASSLOGS5SCALED = self.ENVIRONMENTGRASSLOGS5.subsample(2, 2)
        
        self.ENVIRONMENTICE1 = tk.PhotoImage(file="bin/assets/Environment/Ice/1.png")
        self.ENVIRONMENTICE1SCALED = self.ENVIRONMENTICE1.subsample(2, 2)
        self.ENVIRONMENTICE2 = tk.PhotoImage(file="bin/assets/Environment/Ice/2.png")
        self.ENVIRONMENTICE2SCALED = self.ENVIRONMENTICE2.subsample(2, 2)
        self.ENVIRONMENTICE3 = tk.PhotoImage(file="bin/assets/Environment/Ice/3.png")
        self.ENVIRONMENTICE3SCALED = self.ENVIRONMENTICE3.subsample(2, 2)
        self.ENVIRONMENTICE4 = tk.PhotoImage(file="bin/assets/Environment/Ice/4.png")
        self.ENVIRONMENTICE4SCALED = self.ENVIRONMENTICE4.subsample(2, 2)
        self.ENVIRONMENTICE5 = tk.PhotoImage(file="bin/assets/Environment/Ice/5.png")
        self.ENVIRONMENTICE5SCALED = self.ENVIRONMENTICE5.subsample(2, 2)
        self.ENVIRONMENTICE6 = tk.PhotoImage(file="bin/assets/Environment/Ice/6.png")
        self.ENVIRONMENTICE6SCALED = self.ENVIRONMENTICE6.subsample(2, 2)
        self.ENVIRONMENTICE7 = tk.PhotoImage(file="bin/assets/Environment/Ice/7.png")
        self.ENVIRONMENTICE7SCALED = self.ENVIRONMENTICE7.subsample(2, 2)
        self.ENVIRONMENTICE8 = tk.PhotoImage(file="bin/assets/Environment/Ice/8.png")
        self.ENVIRONMENTICE8SCALED = self.ENVIRONMENTICE8.subsample(2, 2)
        self.ENVIRONMENTICE9 = tk.PhotoImage(file="bin/assets/Environment/Ice/9.png")
        self.ENVIRONMENTICE9SCALED = self.ENVIRONMENTICE9.subsample(2, 2)
        self.ENVIRONMENTICE10 = tk.PhotoImage(file="bin/assets/Environment/Ice/10.png")
        self.ENVIRONMENTICE10SCALED = self.ENVIRONMENTICE10.subsample(2, 2)
        
        self.ENVIRONMENTSTONE1 = tk.PhotoImage(file="bin/assets/Environment/Stone/1.png")
        self.ENVIRONMENTSTONE1SCALED = self.ENVIRONMENTSTONE1.subsample(2, 2)
        self.ENVIRONMENTSTONE2 = tk.PhotoImage(file="bin/assets/Environment/Stone/2.png")
        self.ENVIRONMENTSTONE2SCALED = self.ENVIRONMENTSTONE2.subsample(2, 2)
        self.ENVIRONMENTSTONE3 = tk.PhotoImage(file="bin/assets/Environment/Stone/3.png")
        self.ENVIRONMENTSTONE3SCALED = self.ENVIRONMENTSTONE3.subsample(2, 2)

        self.ENVIRONMENTSTONEDRY1 = tk.PhotoImage(file="bin/assets/Environment/StoneDry/1.png")
        self.ENVIRONMENTSTONEDRY1SCALED = self.ENVIRONMENTSTONEDRY1.subsample(2, 2)
        self.ENVIRONMENTSTONEDRY2 = tk.PhotoImage(file="bin/assets/Environment/StoneDry/2.png")
        self.ENVIRONMENTSTONEDRY2SCALED = self.ENVIRONMENTSTONEDRY2.subsample(2, 2)
        self.ENVIRONMENTSTONEDRY3 = tk.PhotoImage(file="bin/assets/Environment/StoneDry/3.png")
        self.ENVIRONMENTSTONEDRY3SCALED = self.ENVIRONMENTSTONEDRY3.subsample(2, 2)
        self.ENVIRONMENTSTONEDRY4 = tk.PhotoImage(file="bin/assets/Environment/StoneDry/4.png")
        self.ENVIRONMENTSTONEDRY4SCALED = self.ENVIRONMENTSTONEDRY4.subsample(2, 2)

        self.ENVIRONMENTSTONEWET1 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/1.png")
        self.ENVIRONMENTSTONEWET1SCALED = self.ENVIRONMENTSTONEWET1.subsample(2, 2)
        self.ENVIRONMENTSTONEWET2 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/2.png")
        self.ENVIRONMENTSTONEWET2SCALED = self.ENVIRONMENTSTONEWET2.subsample(2, 2)
        self.ENVIRONMENTSTONEWET3 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/3.png")
        self.ENVIRONMENTSTONEWET3SCALED = self.ENVIRONMENTSTONEWET3.subsample(2, 2)
        self.ENVIRONMENTSTONEWET4 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/4.png")
        self.ENVIRONMENTSTONEWET4SCALED = self.ENVIRONMENTSTONEWET4.subsample(2, 2)
        self.ENVIRONMENTSTONEWET5 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/5.png")
        self.ENVIRONMENTSTONEWET5SCALED = self.ENVIRONMENTSTONEWET5.subsample(2, 2)
        self.ENVIRONMENTSTONEWET6 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/6.png")
        self.ENVIRONMENTSTONEWET6SCALED = self.ENVIRONMENTSTONEWET6.subsample(2, 2)
        self.ENVIRONMENTSTONEWET7 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/7.png")
        self.ENVIRONMENTSTONEWET7SCALED = self.ENVIRONMENTSTONEWET7.subsample(2, 2)
        self.ENVIRONMENTSTONEWET8 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/8.png")
        self.ENVIRONMENTSTONEWET8SCALED = self.ENVIRONMENTSTONEWET8.subsample(2, 2)
        self.ENVIRONMENTSTONEWET9 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/9.png")
        self.ENVIRONMENTSTONEWET9SCALED = self.ENVIRONMENTSTONEWET9.subsample(2, 2)
        self.ENVIRONMENTSTONEWET10 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/10.png")
        self.ENVIRONMENTSTONEWET10SCALED = self.ENVIRONMENTSTONEWET10.subsample(2, 2)
        self.ENVIRONMENTSTONEWET11 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/11.png")
        self.ENVIRONMENTSTONEWET11SCALED = self.ENVIRONMENTSTONEWET11.subsample(2, 2)
        self.ENVIRONMENTSTONEWET12 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/12.png")
        self.ENVIRONMENTSTONEWET12SCALED = self.ENVIRONMENTSTONEWET12.subsample(2, 2)
        self.ENVIRONMENTSTONEWET13 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/13.png")
        self.ENVIRONMENTSTONEWET13SCALED = self.ENVIRONMENTSTONEWET13.subsample(2, 2)
        self.ENVIRONMENTSTONEWET14 = tk.PhotoImage(file="bin/assets/Environment/StoneWet/14.png")
        self.ENVIRONMENTSTONEWET14SCALED = self.ENVIRONMENTSTONEWET14.subsample(2, 2)
        
        self.ENVIRONMENTWATER1 = tk.PhotoImage(file="bin/assets/Environment/Water/1.png")
        self.ENVIRONMENTWATER1SCALED = self.ENVIRONMENTWATER1.subsample(2, 2)
        self.ENVIRONMENTWATER2 = tk.PhotoImage(file="bin/assets/Environment/Water/2.png")
        self.ENVIRONMENTWATER2SCALED = self.ENVIRONMENTWATER2.subsample(2, 2)
        self.ENVIRONMENTWATER3 = tk.PhotoImage(file="bin/assets/Environment/Water/3.png")
        self.ENVIRONMENTWATER3SCALED = self.ENVIRONMENTWATER3.subsample(2, 2)
        self.ENVIRONMENTWATER4 = tk.PhotoImage(file="bin/assets/Environment/Water/4.png")
        self.ENVIRONMENTWATER4SCALED = self.ENVIRONMENTWATER4.subsample(2, 2)
        self.ENVIRONMENTWATER5 = tk.PhotoImage(file="bin/assets/Environment/Water/5.png")
        self.ENVIRONMENTWATER5SCALED = self.ENVIRONMENTWATER5.subsample(2, 2)
        self.ENVIRONMENTWATER6 = tk.PhotoImage(file="bin/assets/Environment/Water/6.png")
        self.ENVIRONMENTWATER6SCALED = self.ENVIRONMENTWATER6.subsample(2, 2)
        self.ENVIRONMENTWATER7 = tk.PhotoImage(file="bin/assets/Environment/Water/7.png")
        self.ENVIRONMENTWATER7SCALED = self.ENVIRONMENTWATER7.subsample(2, 2)
        self.ENVIRONMENTWATER8 = tk.PhotoImage(file="bin/assets/Environment/Water/8.png")
        self.ENVIRONMENTWATER8SCALED = self.ENVIRONMENTWATER8.subsample(2, 2)
        self.ENVIRONMENTWATER9 = tk.PhotoImage(file="bin/assets/Environment/Water/9.png")
        self.ENVIRONMENTWATER9SCALED = self.ENVIRONMENTWATER9.subsample(2, 2)
        self.ENVIRONMENTWATER10 = tk.PhotoImage(file="bin/assets/Environment/Water/10.png")
        self.ENVIRONMENTWATER10SCALED = self.ENVIRONMENTWATER10.subsample(2, 2)
        self.ENVIRONMENTWATER11 = tk.PhotoImage(file="bin/assets/Environment/Water/11.png")
        self.ENVIRONMENTWATER11SCALED = self.ENVIRONMENTWATER11.subsample(2, 2)
        self.ENVIRONMENTWATER12 = tk.PhotoImage(file="bin/assets/Environment/Water/12.png")
        self.ENVIRONMENTWATER12SCALED = self.ENVIRONMENTWATER12.subsample(2, 2)
        self.ENVIRONMENTWATER13 = tk.PhotoImage(file="bin/assets/Environment/Water/13.png")
        self.ENVIRONMENTWATER13SCALED = self.ENVIRONMENTWATER13.subsample(2, 2)
        self.ENVIRONMENTWATER14 = tk.PhotoImage(file="bin/assets/Environment/Water/14.png")
        self.ENVIRONMENTWATER14SCALED = self.ENVIRONMENTWATER14.subsample(2, 2)
        self.ENVIRONMENTWATER15 = tk.PhotoImage(file="bin/assets/Environment/Water/15.png")
        self.ENVIRONMENTWATER15SCALED = self.ENVIRONMENTWATER15.subsample(2, 2)
        self.ENVIRONMENTWATER16 = tk.PhotoImage(file="bin/assets/Environment/Water/16.png")
        self.ENVIRONMENTWATER16SCALED = self.ENVIRONMENTWATER16.subsample(2, 2)
        self.ENVIRONMENTWATER17 = tk.PhotoImage(file="bin/assets/Environment/Water/17.png")
        self.ENVIRONMENTWATER17SCALED = self.ENVIRONMENTWATER17.subsample(2, 2)
        self.ENVIRONMENTWATER18 = tk.PhotoImage(file="bin/assets/Environment/Water/18.png")
        self.ENVIRONMENTWATER18SCALED = self.ENVIRONMENTWATER18.subsample(2, 2)
        self.ENVIRONMENTWATER19 = tk.PhotoImage(file="bin/assets/Environment/Water/19.png")
        self.ENVIRONMENTWATER19SCALED = self.ENVIRONMENTWATER19.subsample(2, 2)
        
    def RandomWorldGrass(self, GAMEINSTANCE):
        self.width = GAMEINSTANCE.GAME._current_width
        self.height= GAMEINSTANCE.GAME._current_height
        self.maxRows = int (self.height/128)*5
        self.maxTiles = int (self.width/128)*5
        self.ScaledTileImageGrass = [
            self.ENVIRONMENTGRASS1SCALED, self.ENVIRONMENTGRASS2SCALED,
            self.ENVIRONMENTGRASS3SCALED, self.ENVIRONMENTGRASS4SCALED,
            self.ENVIRONMENTGRASS5SCALED, self.ENVIRONMENTGRASS6SCALED,
            self.ENVIRONMENTGRASS7SCALED, self.ENVIRONMENTGRASS8SCALED,
            self.ENVIRONMENTGRASS9SCALED, self.ENVIRONMENTGRASS10SCALED,
            self.ENVIRONMENTGRASS11SCALED, self.ENVIRONMENTGRASS12SCALED,
            self.ENVIRONMENTGRASS13SCALED, self.ENVIRONMENTGRASS14SCALED,
            self.ENVIRONMENTGRASS15SCALED, self.ENVIRONMENTGRASS16SCALED
        ]
        for row in range(self.maxRows):
            for col in range(self.maxTiles+1):
                offset = 64 if row % 2 == 1 else 0
                x = col * 128 + offset
                y = row * 32
                randomScaledTileImageGrass = random.choice(self.ScaledTileImageGrass)
                self.CANVAS.create_image(x,y,image=randomScaledTileImageGrass,anchor=tk.CENTER)

        